package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	"golang-clean-architecture/internal/delivery/graphql/graph"
	"golang-clean-architecture/internal/delivery/graphql/graph/model"
)

// Currency is the resolver for the currency field.
func (r *itemResolver) Currency(ctx context.Context, obj *model.Item) (*model.Currency, error) {
	panic(fmt.Errorf("not implemented: Currency - currency"))
}

// CreateItem is the resolver for the createItem field.
func (r *mutationResolver) CreateItem(ctx context.Context, input model.CreateItemInput) (*model.Item, error) {
	panic(fmt.Errorf("not implemented: CreateItem - createItem"))
}

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id string) (*model.Item, error) {
	panic(fmt.Errorf("not implemented: Item - item"))
}

// Items is the resolver for the items field.
func (r *queryResolver) Items(ctx context.Context, filter model.ListItemsInput) (*model.ItemPage, error) {
	panic(fmt.Errorf("not implemented: Items - items"))
}

// Item returns graph.ItemResolver implementation.
func (r *Resolver) Item() graph.ItemResolver { return &itemResolver{r} }

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type itemResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
